Feature/formsubmit
marcos-de-barros-vioque/capstone pull request #14
Opened 2022-12-02 11:46 UTC by marcos-de-barros-vioque

Hi!
In this PR I've added the on submit handler to the addspendingform and created the spendings page. 
After having submitted the form, the user is redirected to the spendings page.
From the spendings page, the user can return to the add spendings page by clicking on the "Back" button.
Cheers

2022-12-02 11:52 UTC, stefankorder approved these changes
LGTM!

2022-12-05 10:18 UTC, stefankorder requested changes
LGTM! Please take a look at my comments.

2022-12-05 10:18 UTC, stefankorder commented on components/AddSpendingForm.js
> +  margin-bottom: 100px;
Better use relative units at this point.

2022-12-05 10:18 UTC, stefankorder commented on components/AddSpendingForm.js
>    font-size: 15px;
Better use relative units at this point.

2022-12-05 10:18 UTC, stefankorder commented on components/AddSpendingForm.js
> +  margin: 25px 0 20px 0;
Better use relative units at this point.

2022-12-05 10:18 UTC, stefankorder commented on pages/index.js
> +  margin-top: 200px;
Better use relative units at this point.

2022-12-05 11:08 UTC, stefankorder approved these changes
LGTM!

2022-12-05 11:18 UTC, marcos-de-barros-vioque commented on components/Header.js
> +  margin: 10px 0px 10px 30px;
Thanks @stefankorder ! Should I repost this PR in the code-reviews channel, or rather move to QA?

2022-12-05 11:31 UTC, merged